trigger:
  branches:
    include:
    - v2.1_net5.0
name: 2.1.$(BuildID)$(Rev:.r)-alpha
resources:
  repositories:
  - repository: self
    type: git
    ref: v2.1_net5.0
jobs:
- job: Job_1
  displayName: DAVISOL agent job - Build and deploy dracoon-csharp-crypto-sdk
  pool:
    name: DAVISOL Pipelines
    demands:
    - msbuild
  steps:
  - checkout: self
  - task: DownloadSecureFile@1
    name: snkFile
    displayName: Download secure file
    inputs:
      secureFile: b8a2e8f1-b598-4cb4-be12-ac73524065d8
      retryCount: 5
  - task: NuGetToolInstaller@1
    displayName: Use NuGet 5.11.0
    inputs:
      versionSpec: '5.11.0'
  - task: NuGetCommand@2
    displayName: NuGet restore
  - task: Assembly-Info-NetCore@2
    displayName: Set Assembly Manifest Data
    inputs:
      InsertAttributes: true
      GeneratePackageOnBuild: true
      PackageId: Dracoon.Crypto.Sdk.Net5
      Authors: DRACOON developers, enhancements by DAVISOL GmbH
      Company: Dracoon GmbH
      Product: Dracoon Crypto Sdk for .NET Standard
      Description: A library which implements the client-side encryption of Dracoon, ported to .NET 5.0 and enhanced by DAVISOL GmbH.
      Copyright: Copyright © 2017
      PackageLicenseUrl: https://www.apache.org/licenses/LICENSE-2.0.txt
      PackageProjectUrl: https://github.com/dracoon/dracoon-csharp-crypto-sdk
      PackageIconUrl: https://raw.githubusercontent.com/dracoon/dracoon-csharp-crypto-sdk/master/DracoonCryptoSdk/DracoonCryptoSdk_NugetImage.png
      RepositoryUrl: https://github.com/shuebner20/dracoon-csharp-crypto-sdk/tree/csharpstandard
      PackageTags: dracoon crypto cryptography encryption net5 davisol
      VersionNumber: $(Build.BuildNumber)
      FileVersionNumber: $(Build.BuildNumber)
      InformationalVersion: $(Build.BuildNumber)
      PackageVersion: $(Build.BuildNumber)
  - task: MSBuild@1
    displayName: Build solution **/*.sln
    inputs:
      msbuildArchitecture: x64
      platform: Any CPU
      configuration: Release
      msbuildArguments: /p:SignAssembly=true /p:AssemblyOriginatorKeyFile=$(snkFile.secureFilePath)
      clean: true
  - task: CopyFiles@2
    displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)\lib\net5.0'
    inputs:
      SourceFolder: DracoonCryptoSdk/bin/Release
      Contents: '**/Dracoon.Crypto.Sdk.*'
      TargetFolder: $(Build.ArtifactStagingDirectory)\lib\net5.0
      CleanTargetFolder: true
      OverWrite: true
      flattenFolders: true
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: dracoon-crypto-sdk'
    inputs:
      ArtifactName: dracoon-crypto-sdk
  - task: NuGetCommand@2
    displayName: NuGet pack
    inputs:
      command: pack
      searchPatternPack: DracoonCryptoSdk/DavisolPackage.nuspec
      versioningScheme: byBuildNumber
      includeSymbols: true
      basePath: DracoonCryptoSdk
  - task: NuGetCommand@2
    displayName: NuGet push
    inputs:
      command: push
      feedPublish: 3a11d72e-ad5c-4c0a-bff7-5237610444a0
      allowPackageConflicts: true
...
