trigger:
  branches:
    include:
    - v3.2_net8.0
name: 3.2.$(BuildID)$(Rev:.r)-alpha
resources:
  repositories:
  - repository: self
    type: git
    ref: v3.2_net8.0
jobs:
- job: Job_1
  displayName: DAVISOL agent job - Build and deploy dracoon-csharp-crypto-sdk
  pool:
    name: DAVISOL Pipelines
    demands:
    - msbuild
  steps:
  - checkout: self
  - task: DownloadSecureFile@1
    name: snkFile
    displayName: Download secure file
    inputs:
      secureFile: b8a2e8f1-b598-4cb4-be12-ac73524065d8
      retryCount: 5
  - task: NuGetToolInstaller@1
    displayName: Use NuGet 6.7.0
    inputs:
      versionSpec: '6.7.0'
  - task: NuGetCommand@2
    displayName: NuGet restore
  - task: Assembly-Info-NetCore@2
    displayName: Set Assembly Manifest Data
    inputs:
      InsertAttributes: true
      GeneratePackageOnBuild: true
      PackageId: Dracoon.Crypto.Sdk.Net8
      Authors: DRACOON Developers, enhancements by DAVISOL GmbH
      Company: Dracoon GmbH
      Product: Dracoon Crypto Sdk for .NET Standard
      Description: A library which implements the client-side encryption of Dracoon, ported to .NET Standard 2.0 / .NET 8.0 and enhanced by DAVISOL GmbH.
      Copyright: Copyright © 2021
      PackageLicenseUrl: https://www.apache.org/licenses/LICENSE-2.0.txt
      PackageProjectUrl: https://github.com/DAVISOL-GmbH/dracoon-csharp-crypto-sdk
      PackageIconUrl: https://raw.githubusercontent.com/dracoon/dracoon-csharp-crypto-sdk/master/DracoonCryptoSdk/DracoonCryptoSdk_NugetImage.png
      RepositoryUrl: https://github.com/DAVISOL-GmbH/dracoon-csharp-crypto-sdk/tree/v3.2_net8.0
      PackageTags: dracoon crypto cryptography encryption net6 net8 netstandard2 davisol
      VersionNumber: $(Build.BuildNumber)
      FileVersionNumber: $(Build.BuildNumber)
      InformationalVersion: $(Build.BuildNumber)
      PackageVersion: $(Build.BuildNumber)
  - task: MSBuild@1
    displayName: Build solution **/*.sln
    inputs:
      solution: '**/*.sln'
      msbuildVersion: '17.0'
      msbuildArchitecture: 'x64'
      platform: 'Any CPU'
      configuration: 'Release'
      msbuildArguments: '/p:SignAssembly=true /p:AssemblyOriginatorKeyFile=$(snkFile.secureFilePath)'
      clean: true
  - task: CopyFiles@2
    displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)\lib\net6.0'
    inputs:
      SourceFolder: DracoonCryptoSdk/bin/Release
      Contents: '**/Dracoon.Crypto.Sdk.*'
      TargetFolder: $(Build.ArtifactStagingDirectory)\lib\net6.0
      CleanTargetFolder: true
      OverWrite: true
      flattenFolders: true
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: dracoon-crypto-sdk'
    inputs:
      ArtifactName: dracoon-crypto-sdk
  - task: NuGetCommand@2
    displayName: NuGet pack
    inputs:
      command: pack
      searchPatternPack: DracoonCryptoSdk/DavisolPackage.nuspec
      versioningScheme: byBuildNumber
      includeSymbols: true
      basePath: DracoonCryptoSdk
  - task: NuGetCommand@2
    displayName: NuGet push
    inputs:
      command: push
      feedPublish: 3a11d72e-ad5c-4c0a-bff7-5237610444a0
      allowPackageConflicts: true
...
